import { AdminMetric, AdminShell } from "@/components/admin-shell";

export default function ReportsPage(){
 return <AdminShell active="Reports" title="Reports" subtitle="Track performance, revenue, bookings and operational metrics." actions={<><button className="admin-secondary-button">12 Oct 2024 – 10 Nov 2024</button><button className="admin-secondary-button">Export Report ↓</button></>}>
   <div className="admin-metric-grid"><AdminMetric label="Total Bookings" value="128" meta="↑12%" tone="blue"/><AdminMetric label="Total Revenue" value="₹12,48,000" meta="↑18%" tone="orange"/><AdminMetric label="Total Customers" value="96" meta="↑14%" tone="green"/><AdminMetric label="Conversion Rate" value="24%" meta="↑6%" tone="green"/></div>
   <section className="admin-panel admin-report-chart"><div className="admin-panel-heading"><h2>Bookings & Revenue Trend</h2><span>Last 30 Days⌄</span></div><div className="admin-chart admin-chart--large"><div className="admin-bars">{[38,50,44,61,55,69,59,72,76,64,82,80].map((h,i)=><span key={i} style={{height:`${h}%`}}/>)}</div><svg viewBox="0 0 700 180" preserveAspectRatio="none"><polyline points="0,140 65,115 130,90 195,118 260,83 325,103 390,66 455,74 520,48 585,60 650,35 700,48" fill="none" stroke="#f26b1d" strokeWidth="5"/></svg></div></section>
   <div className="admin-report-bottom"><section className="admin-panel"><div className="admin-panel-heading"><h2>Top Performing Packages</h2><a>View All →</a></div><table className="admin-table"><thead><tr><th>Package</th><th>Bookings</th><th>Revenue</th></tr></thead><tbody>{[["Manali Tour","42","₹4,20,000"],["Rajasthan Heritage","28","₹2,80,000"],["Char Dham Yatra","18","₹1,98,000"],["Kashmir Snow Trip","16","₹1,76,000"]].map((r,i)=><tr key={i}>{r.map(c=><td key={c}>{c}</td>)}</tr>)}</tbody></table></section><section className="admin-panel"><div className="admin-panel-heading"><h2>Fleet Utilization</h2><span>This Month⌄</span></div><div className="admin-donut admin-donut--report"><div>78%<small>Utilized</small></div></div><ul className="admin-legend"><li>In Use <b>78%</b></li><li>Available <b>14%</b></li><li>Maintenance <b>6%</b></li></ul></section></div>
 </AdminShell>;
}
